Movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>/', views.detail, name='detail'),
]

vidly20242/urls.py
from django.contrib import admin
from django.urls import  path, include
from api.models import MovieResource
from . import views

movie_resource = MovieResource()

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('movies/', include('Movies.urls')),
    path('api/', include(movie_resource.urls)),
]

Movies/models.py
from django.utils import timezone
from django.db import models

class Genre(models.Model):
    list_display = ('ID', 'name')
    name = models.CharField(max_length=255)

    def __str__(self):
        return str(self.name)
    
    
class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
# genre = models.ForeignKey(Genre, on_delete=models.SET_NULL, null=True)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title + " " + str(self.release_year) + " " + str(self.number_in_stock) + " " + str(self.daily_rate) + " " + str(self.genre) + " " + str(self.date_created)

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from Movies.models import Movie

# Create your models here.
class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = 'movies'
        excludes = ['date_created']
        

Movies/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Movie

# Create your views here.
from django.http import HttpResponse

def index(request):
    """The home page for Movies"""

    movies = Movie.objects.all()
    # output = ', '.join([m.title for m in movies])
    return render(request, 'movies/index.html', {'movies': movies})
    # return render(request, 'index.html', {'movies': movies})
def detail(request, movie_id):
    """Show a single movie and its details"""

    movie = get_object_or_404(Movie, id=movie_id)
    return render(request, 'movies/detail.html', {'movie': movie})

api/views.py
from django.shortcuts import render

# Create your views here.

vidly20242/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

Movies/templates/movies/detail.html
{% extends "base.html" %}

{% block content %}
<dl>
    <dt>Title</dt>
    <dd>{{ movie.title }}</dd>
    <dt>Genre</dt>
    <dd>{{ movie.genre }}</dd>
    <dt>Stock</dt>
    <dd>{{ movie.number_in_stock }}</dd>
</dl>

{% endblock %}

Movies/templates/movies/index.html
{% extends "base.html" %}

{% block content %}
<table class="table table-striped">
    <tr>
        <th>Title</th>
        <th>Genre</th>
        <th>Number in Stock</th>
    </tr>
    {% for movie in movies %}
    <tr>
        <td><a href="{% url 'movies:detail' movie.id %}">{{ movie.title }}</a></td>
        <td>{{ movie.genre }}</td>
        <td>{{ movie.number_in_stock }}</td>
    </tr>
    {% endfor %}
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <!-- As a heading -->
<nav class="navbar bg-body-tertiary">
    <div class="container-fluid">
      <span class="navbar-brand mb-0 h1">Vidly</span>
    </div>
  </nav>
  <main class="container">
    {% block content %}{% endblock %}
 </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'movies:index' %}">Movies</a>
{% endblock %}